#!/usr/bin/env bash

# Temporary script to use shadowJar while the project is still structured anti-Gradle's expectations.
set -e

# Delete the shadowJar line in the submodule so Gradle doesn't give an error
cd "$(dirname "$0")/DwarfBot"
sed -i.bak '/com.github.johnrengelman.shadow/d' build.gradle
cd ..

# Then add it to the regular project
sed -i.bak '/plugins {/a\'$'\n''    id "com.github.johnrengelman.shadow" version "1.2.3"\'$'\n' build.gradle

./gradlew shadowJar ||
    true # Don't exit the script if the build fails; we still need to revert these files

# return to normal
mv build.gradle.bak build.gradle
cd DwarfBot
mv build.gradle.bak build.gradle
